/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393e",
        "surface-variant": "#333539",
        "surface-container": "#1e2024",
        "surface-container-low": "#1a1c20",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "surface-container-lowest": "#0c0e12",
        "surface-tint": "#ffb4a4",
        "background": "#111317",
        "on-background": "#e2e2e8",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#e4beb6",
        "primary": "#ffb4a4",
        "primary-container": "#ff5733",
        "primary-fixed": "#ffdad3",
        "primary-fixed-dim": "#ffb4a4",
        "on-primary": "#630e00",
        "on-primary-container": "#580c00",
        "on-primary-fixed": "#3d0600",
        "on-primary-fixed-variant": "#8c1800",
        "inverse-primary": "#b72301",
        "secondary": "#b9c8de",
        "secondary-container": "#39485a",
        "secondary-fixed": "#d4e4fa",
        "secondary-fixed-dim": "#b9c8de",
        "on-secondary": "#233143",
        "on-secondary-container": "#a7b6cc",
        "on-secondary-fixed": "#0d1c2d",
        "on-secondary-fixed-variant": "#39485a",
        "tertiary": "#bcc7de",
        "tertiary-container": "#8792a8",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary": "#263143",
        "on-tertiary-container": "#202b3d",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#3c475a",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#ab8982",
        "outline-variant": "#5b403a",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "full": "9999px",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "scan-line": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(160px)" },
        },
      },
      animation: {
        marquee: "marquee 30s linear infinite",
        "scan-line": "scan-line 3s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [],
}
